### ISSUE TITLE
Maquette Interface

### ISSUE THREAD

**Issue by PierreHervelin** [CantinDeBrunoy/run4urlife#1]
Faire une première maquette de l'interface

**Comment by CantinDeBrunoy** [comment]
https://cdn.discordapp.com/attachments/930112841166487614/930808879850348564/unknown.png

**Comment by PierreHervelin** [comment]
![maquette1](https://cdn.discordapp.com/attachments/930123296232574986/930863920514760774/Maquette_1Maquette1.png)
![maquette1-options](https://cdn.discordapp.com/attachments/930123296232574986/930863920330186782/OptionsMaquette1-options.png)
