### ISSUE TITLE
Rajouter le background du menu

### ISSUE THREAD

**Issue by goodfoodtruck** [CantinDeBrunoy/run4urlife#12]
Mettre en place le fond de la page derriere l'interface menu

**Comment by PierreHervelin** [comment]
Je m'occupe d'ajouter les étoiles du background

**Comment by goodfoodtruck** [comment]
https://threejs.org/manual/#en/tips#html-background tips de 2 lignes mais ça peut filer des indices

**Comment by goodfoodtruck** [comment]
Délocaliser le background dans un composant exterieur `background.component.js` avec scope pour savoir si il est dans le menu principal ou le jeu

**Comment by CantinDeBrunoy** [comment]
#55

**Comment by PierreHervelin** [comment]
done
