### ISSUE TITLE
Maquette de la map

### ISSUE THREAD

**Issue by PierreHervelin** [CantinDeBrunoy/run4urlife#2]
Commencer la maquette de la map.

**Comment by CantinDeBrunoy** [comment]
https://cdn.discordapp.com/attachments/930123296232574986/930481490691756032/unknown.png
https://cdn.discordapp.com/attachments/930123296232574986/930477584431591454/unknown.png
https://cdn.discordapp.com/attachments/930123296232574986/930474488884244520/unknown.png

**Comment by PierreHervelin** [comment]
done
