### ISSUE TITLE
[Génération de la map] Création d'une ligne 

### ISSUE THREAD

**Issue by PierreHervelin** [CantinDeBrunoy/run4urlife#6]
### Définir la probabilité d’avoir un objet bloquant
- tirage 0<=x<=1
- x<0.1 = 2 objets bloquants
- x<0.3 = 1 objet bloquant
- sinon 0 objet bloquant
- Les objets bloquant peuvent être placés seulement sur les ligne impaires
- Si line.id <3: 0 objet bloquant

**Comment by Trymal** [comment]
Oui sans souci, j'avais mis ces valeurs au hasard juste pour montrer les probas. On peut évidemment ajuster si il y en a trop ou pas assez
